# Generated by Django 4.1.2 on 2022-10-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delivery_remove_packageitem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='percentage_profit',
        ),
    ]
