# Generated by Django 4.1.2 on 2022-11-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_item_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
