# Generated by Django 4.1.2 on 2022-11-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delivery_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivered',
            new_name='is_delivered',
        ),
    ]
