# Generated by Django 4.2.6 on 2024-08-08 17:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date (e.g., 2022/11/22)')),
                ('institution_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(blank=True, help_text='Phone number of the institution', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the institution', max_length=254, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of the institution', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Description of the bill', max_length=255, null=True)),
                ('payment_details', models.CharField(help_text='Details of the payment', max_length=255)),
                ('amount', models.FloatField(help_text='Total amount due for payment', verbose_name='Total Amount Owing (Ksh)')),
                ('status', models.BooleanField(default=False, help_text='Payment status of the bill', verbose_name='Paid')),
            ],
        ),
    ]
