# Generated by Django 4.2.6 on 2023-11-01 13:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date (eg: 2022/11/22)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='date', unique=True),
        ),
    ]
