# Generated by Django 4.1.2 on 2022-10-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('INA', 'Inactive'), ('A', 'Active'), ('OL', 'On_leave')], default='INA', max_length=12),
        ),
    ]
