# Generated by Django 4.1.2 on 2022-11-09 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_rename_staff_sale_profile'),
        ('accounts', '0003_alter_staff_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['slug']},
        ),
    ]
