# Generated by Django 4.1.2 on 2022-10-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('accounts', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('quantity', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank='True', choices=[('MP', 'MPESA'), ('VISA', 'VISA'), ('CS', 'CASH'), ('VM', 'VOOMA'), ('BK', 'BANK')], max_length=20, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('total_value', models.FloatField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff', verbose_name='Served by')),
            ],
        ),
    ]
