# Generated by Django 4.1.2 on 2022-10-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_received',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.FloatField(default=False),
        ),
    ]
