# Generated by Django 4.1.2 on 2022-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_sale_amount_received_sale_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL')], default='P', max_length=3, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
