# Generated by Django 4.1.2 on 2022-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_purchase_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
