# Generated by Django 4.1.2 on 2022-11-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_sale_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='staff',
            new_name='profile',
        ),
    ]
