# Generated by Django 4.1.2 on 2022-11-18 11:04

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_purchase_slug_sale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='vendor', unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='customer_name', unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
